### PR TITLE
[metadata.themoviedb.org] v5.1.5

### PR DESCRIPTION
**Pull request by pbodq2**
### Description

Added |zh-hk in label="30002" to support information lookup in Chinese - Hong Kong locale.
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by pbodq2** [comment]
Actually I wrote request few months ago via https://forum.kodi.tv/showthread.php?tid=332665

However, I cannot contact the developer directly and no result. I think github is the last choice.

**Comment by Rechi** [comment]
The following version number needs a minor bump, otherwise the Kodi repo won't get the update.
https://github.com/xbmc/repo-scrapers/blob/f3ff4c4125d8caf2f923484d9bf69f5dfc2792e1/metadata.themoviedb.org/addon.xml#L4
\
Also please change the commit message to `metadata.themoviedb.org] v5.1.5`.

**Comment by pbodq2** [comment]
> The following version number needs a minor bump, otherwise the Kodi repo won't get the update.
> [repo-scrapers/metadata.themoviedb.org/addon.xml](https://github.com/xbmc/repo-scrapers/blob/f3ff4c4125d8caf2f923484d9bf69f5dfc2792e1/metadata.themoviedb.org/addon.xml#L4)
> 
> Line 4 in [f3ff4c4](/xbmc/repo-scrapers/commit/f3ff4c4125d8caf2f923484d9bf69f5dfc2792e1)
> 
>  version="5.1.4" 
> 
> 
> Also please change the commit message to `metadata.themoviedb.org] v5.1.5`.

modified per your request.

**Comment by olympia** [comment]
Added outside of this PR.

**Pull request closed without merging**
