### PR TITLE
[metadata.themoviedb.org.python] v1.4.3

### PR DESCRIPTION
**Pull request by mkaflowski**
### Description
Small optimizations for [metadata.themoviedb.org.python].
Possible fix for https://github.com/croneter/PlexKodiConnect/issues/1657 by setting default search_language.
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by enen92** [comment]
@rmrector you were the last one touching the code on the upstream repo. Can you take a look at this? I fear it's again code that didn't went upstream

**Comment by rmrector** [comment]
My goodness, as if submitting to these damned add-on repos wasn't already such a waste of time and energy.

The `<source>` tag in **addon.xml** specifies the upstream repo, then check [its version attribute to see 1.4.0](https://github.com/xbmc/metadata.themoviedb.org.python/blob/master/addon.xml#L4) - neither 1.4.2 or 1.4.3 were upstreamed.

mkaflowski isn't a part of Team Kodi, right (I've been out for a couple weeks so may have missed it)? Team Kodi is the official add-on author (as noted in **addon.xml**), so if not, the rule (from the [wiki](https://kodi.wiki/view/Submitting_Add-ons)) _"Only PRs from the add-on author or his successor will be accepted. Patches should be submitted upstream to the original author first."_ applies, and these should just be closed and redirected upstream straight away.

**Comment by rmrector** [comment]
Closing this. @mkaflowski, please submit all changes upstream. New version submissions for this add-on to the official repo are handled by the author.

**Comment by mkaflowski** [comment]
Ok. Very sorry for my mistake.

**Comment by rmrector** [comment]
No worries, I do appreciate the change. I'm frustrated at the process, not you or your effort.

**Pull request closed without merging**
