### PR TITLE
update tv-tmdb and theaudiodb icons

### PR DESCRIPTION
**Pull request by uNiversaI**
tmdb-tv icon was left stale in https://github.com/jmarshallnz/metadata.tvshows.themoviedb.org/pull/2 until I realised no one was coming to the rescue.

The other just matches the previously done to theaudiodb.

### CODE REVIEW

**Comment by mkortstiege** [comment]
Thanks. @da-anda your button.

**Comment by da-anda** [comment]
why not reuse the already existing TMDb icon? https://github.com/xbmc/repo-scrapers/blob/gotham/metadata.themoviedb.org/icon.png or at least sync them?

**Comment by uNiversaI** [comment]
one is TV the other not

**Comment by da-anda** [comment]
still one is having a "meta data...." subline, the other not (I thought you don't like inconsistency ;) ). Also the "TV" should be "TV shows" as it's way to subtile IMO, and the other would then need a "movies" tag, no? Or simply use the same icon for both, as they are listed in different add-on categories anyways.

**Comment by uNiversaI** [comment]
Yes I thought about that, OK.

**Comment by uNiversaI** [comment]
OK its done, both should be like the others style.

**Comment by uNiversaI** [comment]
OK done both look same style & also fixed the existing the "h" slightly up on themoviedatabase.org text.

**Comment by da-anda** [comment]
@mkortstiege I hand the button back to you as I only have a green comment button to press :)

**Comment by MartijnKaijser** [comment]
Know your place @da-anda ;)

**Comment by da-anda** [comment]
@MartijnKaijser I didn't ask to be pinged :P

**Pull request merged**
