### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud/projects/kodi-add-ons-information-providers/metadata-album-universal/)
for Kodi add-ons: information providers/metadata.album.universal.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by enen92** [comment]
@gade01 should this get in? Odd that we get translations directly pushed to the repo. Shouldn't it go upstream instead?

**Comment by gade01** [comment]
@enen92 I talked about this with @olympia some time ago, who told me Weblate should be hooked directly up to this repo.

**Comment by enen92** [comment]
Hum I guess you're right, those addons don't have a `<source>` tag in addon.xml. Maybe we should move them to the org or to https://github.com/xbmc-addons

**Comment by gade01** [comment]
@enen92 Fine with me.
Please ping me if you do, so I can move Weblate as well.

**Comment by razzeee** [comment]
You'll need to get @olympia on your side, if you want to do that. It might be far more complicated for them.

**Comment by olympia** [comment]
Right, thanks @razzeee. Please don't move the scrapers from where they are.
I am still fine translations to be pushed directly to this repo. I don't really get what is the technical issue here...

**Comment by enen92** [comment]
There's no technical issue, is a matter of consistency and the message we, as a team, convey to the outside. We use these repos (repo-plugins, repo-scripts, repo-scrappers, etc) as "container" for all addons (used by repo-generator) and tell users/contributors to submit their fixes upstream so the author can then push the aggregate (a new version) to the repo. This implies addons have an upstream location (identified by the `<source>` tag in addon.xml) so we know where to contribute. Pushing translations or fixes directly to this repo without a version bump just bypasses the whole process.

But whatever, I don't really care. Just take note of our approach here the next time someone pushes some update to the repo without bringing the changes upstream (https://github.com/xbmc/repo-scrapers/pull/314#issuecomment-944950276).

**Comment by olympia** [comment]
Thanks @enen92 for the explanation. Well, scrapers were always on a drifting track :) 
Since due to the python scrapers I will be out of business sooner or later, if someone takes over the maintenance of the XML scrapers, then I can and ready to step down. Just let me know :)

As for the translation I fully agree though that those shouldn't be pushed without version bumps. Who knows when will be the next time that given scraper is touched by another commit and those translations wouldn't be picked up till then.

**Comment by gade01** [comment]
@olympia I bump the scraper versions with this action from time to time when translations are merged: https://github.com/xbmc/repo-scrapers/blob/leia/.github/workflows/increment-version.yml

**Review by gade01 — APPROVED** [review]

**Pull request merged**
