### PR TITLE
Themes for skin Aeon MQ

### PR DESCRIPTION
**Pull request by AeonMQ**
Compatible with skin Aeon MQ 7 and higher.

### Checklist:

- [X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md) document
- [X ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
You have to move your addon into a directory with the addon id as name and aren't allowed to touch other files.

Also you have checked `Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0`, but your commit message tells `Themes for skin Aeon MQ`.

If you need some help with git just ask.

**Comment by AeonMQ** [comment]
I made the necessary corrections. Sorry for the confusion.

**Comment by Rechi** [comment]
Still not correct as you remove all other addons in your PR.

**Comment by AeonMQ** [comment]
I'm sorry but I do not see any other add-on. Do you think I'd better erase everything and start from scratch? As you can see I do not have much affinity with git.

**Comment by Rechi** [comment]
Do the following to correct this PR
```
git checkout resource.images.skinthemes.aeonmq-v0.0.3
git reset --hard HEAD~2
mkdir resource.images.skinthemes.aeonmq
 --- now copy the addon files into that directory ---
git add -- resource.images.skinthemes.aeonmq
git commit -m '[resource.images.skinthemes.aeonmq] v.0.0.3'
git push -f
```

P.S. Is there any reason to not update the version of this addon in jarvis branch?

**Comment by AeonMQ** [comment]
Is there any way to do this by the GIT application using windows?

The add-on is compatible with Jarvis, it was my mistake, there is no reason not to update it.

**Comment by AeonMQ** [comment]
I did the process via the command line but some errors occurred.

**Comment by Rechi** [comment]
I can't help without knowing the error message.

**Comment by AeonMQ** [comment]
E:\Downloads\repo-scrapers>git reset --hard HEAD~2
error: unable to stat just-written file .empty: No such file or directory
error: unable to stat just-written file .gitattributes: No such file or directory
error: unable to stat just-written file .gitignore: No such file or directory
error: unable to stat just-written file README.md: No such file or directory
error: unable to stat just-written file info.txt: No such file or directory
Unlink of file 'metadata.artists.universal' failed. Should I try again? (y/n) y
Unlink of file 'metadata.artists.universal' failed. Should I try again? (y/n) n
warning: unable to unlink 'metadata.artists.universal': Directory not empty
fatal: cannot create directory at 'metadata.artists.universal': Directory not empty

**Comment by Rechi** [comment]
Have you updated to Git 2.16.0?
I had the same error and downgrading to [2.15.1](https://github.com/git-for-windows/git/releases/tag/v2.15.1.windows.2) solved it again.

**Comment by AeonMQ** [comment]
More one:
E:\Downloads\repo-scrapers>git commit -m '[resource.images.skinthemes.aeonmq] v.0.0.3'
error: pathspec 'v.0.0.3'' did not match any file(s) known to git.

**Comment by AeonMQ** [comment]
Ps. Now I am using version 2.15.1

**Comment by Rechi** [comment]
Try again with `git commit -m "[resource.images.skinthemes.aeonmq] v.0.0.3"` or if it still doesn't work commit from GUI and then continue with next command in the command line.

**Comment by AeonMQ** [comment]
Great, all right now.

**Comment by Rechi** [comment]
No still wrong, did you execute exactly `git reset --hard HEAD~2`?

**Comment by AeonMQ** [comment]
yes but I will do it again.

**Comment by AeonMQ** [comment]
E:\Downloads\repo-scrapers>git reset --hard HEAD~2
HEAD is now at 78bf5caa [metadata.universal] updated to v5.1.1

This is wrong, is not it?

**Comment by Rechi** [comment]
This is correct.
You had two commits in your PR, one that accidentally removed all addons and the second where you added (moved) your addon.

`git reset --hard HEAD~2` just completely removed those two commits.

**Comment by AeonMQ** [comment]
okay, but the metadata.universal add-on is not mine okay !?

All done.

**Comment by olympia** [comment]
Guys, you know this PR is against the scraper repo which is not correct, right?

**Comment by MartijnKaijser** [comment]
To also add. Aeon MQ7 skin is even in our repo so why should we add this update?
Last MQ skin update was for Isengard so I can't see the point.

**Comment by Rechi** [comment]
@olympia thanks for the info
I noticed it at the previous PR (#69) and only asumed it was correct now.

**Comment by Rechi** [comment]
This addon already exist in our repos at https://github.com/xbmc/repo-resources/tree/jarvis/resource.images.skinthemes.aeonmq

**Comment by AeonMQ** [comment]
Hello Martijn, how are you? You are correct, although the skin is not in the repo, this add-on is used in the Aeon MQ 7. However my intention is to prepare things for Aeon MQ 8 (Leia) that should be ready very soon.

PS. Yes, the add-on already exists, my intention was just to update, sorry for the mess I caused.

**Comment by AeonMQ** [comment]
My concern is that the current add-on contains copyrighted images. This update fixes this. But no problem, we'll talk again soon.

**Pull request closed without merging**
