### PR TITLE
[themoviedb] cache api response when using imdb based lookups

### PR DESCRIPTION
**Pull request by mkortstiege**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
added you to the repo group :)

**Comment by mkortstiege** [comment]
Thanks ;)

**Comment by mkortstiege** [comment]
How do we handle scraper core scraper pulls these days? Push to scrapers and sync to master when preparing a new tag/release?

**Comment by MartijnKaijser** [comment]
repo is still upstream and once in a while we sync

**Pull request merged**
