### PR TITLE
Multiple ratings and uniqueids

### PR DESCRIPTION
**Pull request by ScudLee**
Following from the previous PR #63, this updates the tvdb scraper and the Universal scraper to use the new ratings code and switch to uniqueids, and also use the premiered date for Universal. (Obviously this then supersedes PR #35.)

There's also an edge case bugfix in there for absolute episode ordering (but don't worry too much about that).

@olympia, @phate89, @Razzeee (again) to check, thanks.
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by olympia** [comment]
@ScudLee, could you please bump versions for UMS and TVDb to 4.0.0 and 3.0.0 respectively?

**Comment by ScudLee** [comment]
It should be fine as long as they're a higher version.  It doesn't need to be a whole version bump.

**Comment by MartijnKaijser** [comment]
You should keep enough room to not accidentally have gotham overrule krypton. Having big version bump also makes it more clear what you're using

**Comment by ScudLee** [comment]
Fair enough.

Are you sure UMS to 4.0.0, not 3.0.0?  That's not a typo?  It's only 2.8.11 currently.

**Comment by olympia** [comment]
Yes, I want to keep room for version numbers for future backports.

**Comment by olympia** [comment]
without going down the route ending up with version numbers 2.8.156.897 :)

**Comment by ScudLee** [comment]
Done.

**Comment by olympia** [comment]
Thanks ScudLee

**Pull request merged**
