### PR TITLE
Align order of result to new tmdb behavior

### PR DESCRIPTION
**Pull request by Razzeee**
For reference see the email travis send (even if he is pointing at something else, but this seems to have also changed and actually broken it).
Maybe we should wait for him, so that he can say that it will be kept like this.

Fixes the problem for me, but testing scrapers is hard.

### CODE REVIEW

**Comment by ronie** [comment]
ping @olympia

**Comment by ronie** [comment]
please do a version bump a well.

**Comment by neurolit** [comment]
I tried this commit (as my scraper was out of order since TMDB changes) but now it finds wrong movies (instead of not finding any).

**Comment by shiggity** [comment]
see my comments at http://forum.kodi.tv/showthread.php?tid=228154&pid=2159342#pid2159342

the regex output order is wrong and you put in a capturing group i don't think you need

**Comment by shiggity** [comment]
Diff: https://github.com/xbmc/repo-scrapers/compare/gotham...shiggity:gotham?expand=1

**Comment by olympia** [comment]
Fixed in v3.8.6

**Comment by MartijnKaijser** [comment]
@olympia are tvshows also affected by this problem?
thx for the fix (will test tonight)

**Comment by neurolit** [comment]
Hi @olympia, thanks for the fix. I tested it, it works perfectly!

**Comment by MartijnKaijser** [comment]
seems some report that there are still some minor issues
http://forum.kodi.tv/showthread.php?tid=228154&pid=2160237#pid2160237

**Comment by MartijnKaijser** [comment]
@olympia seems users are having mixed descriptions (english+french) with 3.8.7 version (and before)
http://forum.kodi.tv/showthread.php?tid=228154&pid=2160623#pid2160623

**Comment by olympia** [comment]
This is just one and only random user with an issue I can't reproduce... :)

**Comment by MartijnKaijser** [comment]
all good then :)
thx for the fixes

**Comment by MartijnKaijser** [comment]
@olympia oh i haven't tried the TVshow scraper yet if that suffered from the same problems

**Comment by olympia** [comment]
I did ;) Seems to be not impacted.

**Pull request closed without merging**
