### PR TITLE
[metadata.tvdb.com] updated to v2.0.5

### PR DESCRIPTION
**Pull request by ScudLee**
### Description
Apparently Kodi doesn't clear headers between requests during a scrape, so the (capitalised) Accept-Language from the TVDB scraper was interfering with the (all lower-case) accept-language from the IMDb scraper.

Avoided by simply making the TVDB scraper use all lower-case too.

You can still verify the larger issue by turning on libcURL component logging and scraping a show with IMDb ratings, then noting that the Authorization header from the TVDB URLs is also being sent to IMDb.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by olympia** [comment]
Merged

**Comment by Razzeee** [comment]
Did you test this on Linux?

**Comment by ScudLee** [comment]
Do you mean the scraper fix, or the larger issue?

Because I can't see how the scraper fix can break.  At worst it was non-issue if on Linux the headers were treated either case-insensitive or cleared properly.
(But no, I haven't tested on Linux.)

**Comment by Razzeee** [comment]
Never mind. Linux is just known for being case sensitive. But as you had to fix that for windows too it should be fine.

**Comment by ScudLee** [comment]
The major case-sensitivity issue was whether TVDB would allow the lower-cased accept-language.

We'd have been screwed if that hadn't worked.

**Comment by olympia** [comment]
We could have still tried to amend the imdb one... :) we'd have been screwed if one was only working with lower case while the other one with only with capitalized... but all fine.

@ScudLee, thank you for all your amazing work on this! By the way, don't you have direct commit access to repo-scrapers? I think you had and definitely you should have that?

**Comment by ScudLee** [comment]
I had access when they were on Sourceforge(?)  Seems a long time ago.
I don't think I was around much when the move to Github happened.
I'm not particularly bothered, I always found unfettered access a little unnerving.
PR-as-sanity-check is preferable.

**Pull request merged**
