### PR TITLE
[metadata.tvdb.com] v3.1.0

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description
This adds the ability to use metadata from fanart.tv to fetch additional artwork such as cleararts.
~~It also removes the ineffective setting labeled `Enable Fanart`.~~
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by Rechi** [comment]
What's the reason for not updating the version in krypton branch?

> Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

please follow this rule

**Comment by AMoo-Miki** [comment]
I noticed that when fanart.tv was added to the TMDB one, they bumped it to Leia. I presumed there was some reason for that and followed suit. If you still feel it should be added to Krypton branch, please lemme know and I will raise the PR there.

**Comment by Rechi** [comment]
> I noticed that when fanart.tv was added to the TMDB one, they bumped it to Leia. I presumed there was some reason for that and followed suit. If you still feel it should be added to Krypton branch, please lemme know and I will raise the PR there.

@olympia can you give the reason why it was done like that for metadata.tvshows.themoviedb.org and if fanart should be added for only in leia or in krypton too for metadata.tvdb.com.


> By the way, does Krypton handle the new language folder layout?

Yes, that's supported since Isengard.

**Comment by olympia** [comment]
That's because Krypton doesn't support scraping the extra artwork like clearart, discart and co. (It's not about fanart, it's about art from fanart.tv). 

...but I don't even see what has been added/ changed. There is clearly an issue with EOL formatting in this PR.

**Comment by AMoo-Miki** [comment]
@olympia thanks for taking a look. I have not changed the line endings; they are all LFs. I think the reason you can't see the diff clearly is that the folder names have been changed to match the new language folder structure.

**Comment by olympia** [comment]
Can you amend the PR that there is only one change at a time and the diff can be seen clearly? I am anyway not very motivated to touch this scraper, but in this way, without seeing the changes I surely won't merge. Thank you.

**Comment by AMoo-Miki** [comment]
Sure. I did the language changes only because the CI on this branch fails the build.

**Comment by Razzeee** [comment]
> btw, if the goal is to gradually move away from TVDB, let's simply abandon this change.

Means let's close this?

**Pull request closed without merging**
