### PR TITLE
Update albumuniversal.xml

### PR DESCRIPTION
**Pull request by elrodro83**
Proper scraping of "Official" releases that may have a "disambiguation" attribute. For instance:

http://musicbrainz.org/release-group/e03b8357-68c8-4f88-b21b-7ba470e9bda1
http://search.musicbrainz.org/ws/2/release/?fmt=xml&query=release:%22Live%20Cologne%201994%22%20AND%20(artistname:%22Colosseum%22%20OR%20artist:%22Colosseum%22)

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@olympia @mkortstiege ping

**Comment by olympia** [comment]
Can you please add version history and bump version in addon.xml accordingly?

**Comment by elrodro83** [comment]
@olympia done!

**Comment by olympia** [comment]
OK, thanks! Pushed, cheers!

**Comment by MartijnKaijser** [comment]
@elrodro83 this broke scraping in a really bad way and started spamming the fanart.tv servers with empty MBID.
As such this is reverted

**Comment by elrodro83** [comment]
@MartijnKaijser Could it have been broken by this change? I just added an expected tag in the regexps for musicbrainz data.

Do you have some way to retest this after reverting the change?

**Comment by MartijnKaijser** [comment]
i reverted this change and it fixed the issue i had. 
Not albums have the MBID in the database and that ended up like this
http://webservice.fanart.tv/v3/music/albums/?api_key=xxxxxxxx
See the MBID missing as it should look like this
http://webservice.fanart.tv/v3/music/albums/xxxxxxxxxxx?api_key=xxxxxxxxx

Simple do the change you had local and refresh one album and look at the debuglog

**Comment by elrodro83** [comment]
Weel, i think i have found the issue.

I followed your setps to reproduce this, but found that the error was appearing at randon in both 2.4.0 and 2.4.1. After looking at the logs, i found the first difference (being precicely the missing MB release id) after querying the release info from MusucBrainz. In the case i was using for testing, taht url was

http://musicbrainz.org/ws/2/release/d672b67d-ae44-4f0b-ae43-7af59e8f7083?inc=recordings+release-groups+artists+labels+ratings

Now, if you query that url with a browser a couple of times, you will see that the header for the "release-group" tag return the "id" and "type" in a random order each time. The scraper is expecting type first and then the id (https://github.com/elrodro83/repo-scrapers/blob/2691fdf16f8329ac1aaf3fee94e18f693d224231/metadata.album.universal/albumuniversal.xml#L64)

So, i'd bet that thue issue you pointed out will continue to happen even with the revert.

The proper fix would be for the scraper (at least this part i linked before) to be able to process tag attributes regardless of its order. Maybe regexps fall short for this and a refactor to use xslt would be needed.

**Comment by olympia** [comment]
All should be now resolved with v2.5.0

**Comment by elrodro83** [comment]
Cool!

**Pull request merged**
