### PR TITLE
[metadata.themoviedb.org] updated to v4.0.0

### PR DESCRIPTION
**Pull request by phate89**
I updated the scraper to add the type and multiple ratings and uniqueid support from v17

It needs to be in krypton repo because since ratings are retrieved from a function (so not in one xml file) the backward compatibility might kick in.

Needs https://github.com/xbmc/repo-scrapers/pull/32 and https://github.com/xbmc/repo-scrapers/pull/33

### CODE REVIEW

**Comment by Razzeee** [comment]
I would like to get this merged

**Comment by phate89** [comment]
The problem is that noone can review them properly and I'm the only one that tested them..

**Comment by MartijnKaijser** [comment]
@olympia could you have a look?

**Comment by olympia** [comment]
I am looking at this, but it's non-trivial as we need to split versions pre & post Krypton and we will need to maintain both. I will try to figure this out.

**Comment by olympia** [comment]
is there any skin displaying multiple ratings to test with?

**Comment by Razzeee** [comment]
No, not that I'm aware of, as this would be the basis for most skinners to get this going. There might be some scripts that already try to use this, but you won't see it in any frontend.

**Comment by olympia** [comment]
Pushed here:
https://github.com/xbmc/repo-scrapers/commit/d9c6b46df18e02b3619f24a371bd1e12808e6af2

**Pull request closed without merging**
